services:
  nextjs:
    container_name: nextjs-app
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /app
    ports:
      - '3000:3000'
    volumes:
      - .:/app:delegated
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
      - TAILWIND_MODE=watch
    command: npm run dev
    restart: unless-stopped
