FROM node:20-alpine

WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer les dépendances (inclut dev par défaut)
RUN npm install

# Copier le code source
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]