import type { Metadata } from 'next';

export const metadata: Metadata = {
  // ✅ Technique standard
  colorScheme: 'light dark',
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#ffffff' },
    { media: '(prefers-color-scheme: dark)', color: '#0b1220' },
  ],
  
  // Autres metas
  title: 'FKB Frankenbike',
  description: 'Generated by create next app',
};
